### ISSUE TITLE
Consider using DataTables for viewing DataFrames.

### ISSUE THREAD

**Issue by blois** [sbooeshaghi/SBA-PPP-Loan-Data#2]
Thank you very much for putting together these notebooks!

For some of these it may be useful to enable Colab's DataTable display for dataframes, just makes the results a bit easier for some people to navigate-

```python
from google.colab import data_table
data_table.enable_dataframe_formatter()
```

For example: https://colab.research.google.com/gist/blois/7b166b7204f8c68dfe8b085efda76024/data_summary.ipynb

**Comment by sbooeshaghi** [comment]
Oh wow very cool! I just replaced data_summary.ipynb with the notebook you linked. Thank you for the suggestion, it makes the tables much easier to navigate.
